[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5"
dotenvy = "0.15"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls", "cookies", "gzip", "brotli"] }
clap = { version = "4.4", features = ["derive"] }
